name: Github workflow with authentication and authorization

on: 
  repository_dispatch:
    types: ["github-workflow-test"]

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Save github event to file
        run: |
          echo '${{ toJSON(github.event)}}' > payload.json
          
      - name: Authenticate
        uses: akita-cicd/akita@v1

      - name: Execute after authenticated
        run: |
          echo "Successfully authenticated ${{ github.event.client_payload.workflowInputs.text }}"
